# Generated by Django 4.1.4 on 2022-12-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_date_news_date_of_update_news_date_of_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/images/%Y/%m/%d/'),
        ),
    ]
